### ISSUE TITLE
Set reduction / minimization

### ISSUE THREAD

**Issue by kdeldycke** [trouchet/eule#120]
### Description

Here is a collection of overlapping sets grouping platforms by their family:

```python
GROUPS = {
    "all_platforms": [
        "aix",
        "cygwin",
        "freebsd",
        "hurd",
        "linux",
        "macos",
        "netbsd",
        "openbsd",
        "solaris",
        "sunos",
        "windows",
        "wsl1",
        "wsl2",
    ],
    "all_windows": [
        "windows",
    ],
    "unix": [
        "aix",
        "cygwin",
        "freebsd",
        "hurd",
        "linux",
        "macos",
        "netbsd",
        "openbsd",
        "solaris",
        "sunos",
        "wsl1",
        "wsl2",
    ],
    "unix_without_macos": [
        "aix",
        "cygwin",
        "freebsd",
        "hurd",
        "linux",
        "netbsd",
        "openbsd",
        "solaris",
        "sunos",
        "wsl1",
        "wsl2",
    ],
    "bsd": [
        "freebsd",
        "macos",
        "netbsd",
        "openbsd",
        "sunos",
    ],
    "bsd_without_macos": [
        "freebsd",
        "netbsd",
        "openbsd",
        "sunos",
    ],
    "all_linux": [
        "linux",
    ],
    "linux_layers": [
        "wsl1",
        "wsl2",
    ],
    "system_v": [
        "aix",
        "solaris",
    ],
    "unix_layers": [
        "cygwin",
    ],
}
```

Now I want to have a magic function that can take an arbitrary list of platforms, and return the minimal set of families that cover the provided platforms.

And if there is no solution perfectly overlapping the initial set, I want the function to return the best set of families + remaining platforms that cover the provided set. While minimising the total number of items in the solution.

### What I Did

In fact, I already implemented this in [Click Extra](https://github.com/kdeldycke/click-extra) as part of [my platform detection utilities](https://kdeldycke.github.io/click-extra/platforms.html).

See for instance:
- The sets of [OS families and other groups](https://kdeldycke.github.io/click-extra/platforms.html)
- [My `reduce()` method](https://github.com/kdeldycke/click-extra/blob/d52826fd268cd13dbf3bd64e5d83a9b0dacf9590/click_extra/platforms.py#L495-L563) that does exactly what I describe in the section above.
- The [test cases](https://github.com/kdeldycke/click-extra/blob/d52826fd268cd13dbf3bd64e5d83a9b0dacf9590/click_extra/tests/test_platforms.py#L285-L323) demonstrating my implementation results.

My implementation in Click Extra is fancier than the `GROUPS` dictionary above: [platforms](https://github.com/kdeldycke/click-extra/blob/d52826fd268cd13dbf3bd64e5d83a9b0dacf9590/click_extra/platforms.py#L147-L168) and [OS families](https://github.com/kdeldycke/click-extra/blob/d52826fd268cd13dbf3bd64e5d83a9b0dacf9590/click_extra/platforms.py#L211-L282) are richer objects.

I simplified the `GROUPS` example above to make it ready-to-use for `eule`. Note that family and platform names are unique and do not overlap to simplify the dataset.

I'm pretty sure what I'm trying to do has already been solved and an optimal algorithm has already been written 50 years ago by Donald Knuth or someone else. 😅

My instinct tells me that this is a well-known problem, and that there is a better way to solve it. It probably has a more precise name other than `reduce` or `minimize` in the fields of set theory or graphs. 😬

At the end I already have a naive algorithm that works, but rely on heuristics and brute force to find the best solution. I guess I should try to re-implement it using some of the `eule` helpers. Does `eule` provides enough primitives to make my method more straightforward?

BTW, are *spider set space* (desribed in #52) the answer to my use-case?

**Comment by brunolnetto** [comment]
I ask you to correct me if I cannot understand: we have the dictionary with platforms. The key  `all_platforms` has union without repetition of all other key values, and may be left over. In this data, we want the minimal set of families, in this case, the _keys of the dictionary_ except for key `all_platforms`, that cover the provided platforms.

By definition, the method `euler` on library `eule` will take your dicionary and find the  non-empty intersections. In case you seek the key for each set, the utilitary is `euler_keys`. For the boundaries between intersections, you require the utilitary `euler_boundaries`.

![image](https://github.com/trouchet/eule/assets/13961685/c371211a-2c03-42ce-aae6-c0131467d38b)

The code below outputs the following results:

```python
# Families
GROUPS_COLUMNS=[k for k in GROUPS.keys() if k != 'all_platforms']
print('GROUPS columns: '+str(GROUPS_COLUMNS))

# Platforms
GROUPS_VALUES=[]
for k, i in GROUPS.items():
    GROUPS_VALUES=GROUPS_VALUES+i
    
GROUPS_VALUES=list(set(GROUPS_VALUES))
print('GROUPS platforms: '+str(GROUPS_VALUES))

# Has key `all_platforms` overlapping to non-repetitive union of
# values of remaining values
is_overlapping=len(list(set(GROUPS['all_platforms']) - set(GROUPS_VALUES)))==0

print('Is overlapping: '+str(is_overlapping))

families={k: i for k, i in GROUPS.items()  if k != 'all_platforms'}

print('Euler sets: '+str(euler(families)))
```

Output:

```
GROUPS columns: ['all_windows', 'unix', 'unix_without_macos', 'bsd', 'bsd_without_macos', 'all_linux', 'linux_layers', 'system_v', 'unix_layers']
GROUPS platforms: ['cygwin', 'netbsd', 'sunos', 'wsl2', 'windows', 'freebsd', 'wsl1', 'openbsd', 'solaris', 'macos', 'linux', 'hurd', 'aix']
Is overlapping: True
Euler sets: {('unix', 'unix_without_macos'): ['hurd'], ('system_v', 'unix', 'unix_without_macos'): ['solaris', 'aix'], ('linux_layers', 'unix', 'unix_without_macos'): ['wsl1', 'wsl2'], ('all_linux', 'unix', 'unix_without_macos'): ['linux'], ('unix', 'unix_layers', 'unix_without_macos'): ['cygwin'], ('bsd', 'bsd_without_macos', 'unix', 'unix_without_macos'): ['openbsd', 'freebsd', 'netbsd', 'sunos'], ('bsd', 'unix'): ['macos'], ('all_windows',): ['windows']}
​```

Is it by any case somewhat you look for?

**Comment by brunolnetto** [comment]
@kdeldycke I will start a time out from now to a week in the future for closing this issue. Do you agree?

**Comment by brunolnetto** [comment]
Hmmm, I see. Is the deadline anyhow pushy? I can do it, but a general implementation may require some thinking, and simplification. As you mentioned, spider sets may be useful for the method `match`. You list the following methods for class `Euler`:

- `as_dict`: convert families on Euler sets dictionary object;
- `match`: seek sets with the provided items (See Remark 1). 
- `remove_region_key`: Remove a set key and its items. If there is an exclusive item of this set, it will be removed from Euler set space.  
- `sub_space`: Similar to match. 

_Remark 1_: On example with single item `{'wsl1'}`, your expected result to be an empty set. Why? Do you expect the user to provide the exact items of existent Euler set. It seems less reasonable than find the available families with those desired items, like you later point on method `sub_space`. What do u think? 

_Remark 2_: Method `remove_region_key` is equivalent to delete respective key on original set. Is it so?

**Comment by brunolnetto** [comment]
For the sake of clarity, let us

**Comment by brunolnetto** [comment]
@kdeldycke Checkout the new release 1.0.2. Sorry, but I am still uncertain about method `subspace`. :-/

```
from eule import euler, Euler

# Euler instance
big_space = Euler(families)

print('\n')

# as dictionary
print(big_space.as_dict())

print('\n')

# Dunder method __getitem__ 
print(big_space['bsd'])

print('\n')

# Method match 
print(big_space.match({'openbsd', 'freebsd', 'netbsd', 'sunos'}))
print(big_space.match({'openbsd', 'freebsd', 'netbsd', 'sunos', 'macos'}))
print(big_space.match({'wsl1'}))
print(big_space.match({'wsl1', 'wsl2'}))

print('\n')

# Method remove_region_key
big_space.remove_key('linux_layers')
big_space.as_dict()
```

**Comment by brunolnetto** [comment]
@kdeldycke The new release resolves your proposal except for method `sub_space`. This method requires clarification from my side. Do you mind explaining ir once again?

**Comment by brunolnetto** [comment]
@kdeldycke I will close this method since I received no further response within two months. Thanks for suggestions though!

**Comment by kdeldycke** [comment]
Thanks @brunolnetto for the implementation of the `Euler` class! I'll play with it and see how I can make good use of that one. Will keep you posted on my discoveries.
